AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'SWAP SAM Dev'
Resources:
  P3:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          /haats:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SwapSAM.Arn}/invocations
              responses: {}
  SwapSAM:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: haatp3-dev
      Handler: index.lambda_handler
      Runtime: python2.7
      CodeUri: ./extractSquads
      Description: haatp3
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: haats
            Method: get
            RestApiId:
              Ref: P3
  Member:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: guildName
          AttributeType: S
        - AttributeName: memberName
          AttributeType: S
      KeySchema: 
        - AttributeName: guildName
          KeyType: HASH
        - AttributeName: memberName
          KeyType: RANGE
      TableName: member_dev
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  Roster:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: memberName
          AttributeType: S
        - AttributeName: toonName
          AttributeType: S
      KeySchema: 
        - AttributeName: memberName
          KeyType: HASH
        - AttributeName: toonName
          KeyType: RANGE
      TableName: toon_dev
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1